//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuznetsovAutoservice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public Cars()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int CarID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string LicensePlate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
